
@startuml components
    skin rose

    [Viewer\n(Client)] as V

    component "Cloud Storage" {
        [World\nRepository] as WR
        port "HTTP(s)" as WR_HTTP
        WR <-- WR_HTTP
    }
    
    component "World Server" {
        database {
            [User\ndatabase] as DB
        }
        [World Server\nCore] as WS

        WS --> DB
        port UDP as WS_UDP
        port "HTTP(s)" as WS_HTTP
        WS <-up- WS_UDP
        WS <-right- WS_HTTP
    }

    V --> WR_HTTP
    V --> WS_UDP
    V --> WS_HTTP
@enduml

@startuml Movement_Pose_Seq
    skin rose
    participant User as "User input\ndevice"
    participant c1 as "User's\nClient"
    participant c2 as "Other's\nClients"
    participant Server as "World\nServer"

    User ->> c1 ++ : movement
    note left of c1 #ff8888 : Need low \nlatency !

    c1 -> c1 ++ : movement
    note left of c1 : precompute IK\nfor complete pose
    return  complete\npose
    c1 ->> Server ++ : Avatar pose\nchange
    deactivate c1

    note left of Server : Announce user's\nmovement
    Server ->> c2 ++ : Pose propagation
    deactivate Server

    c2 -> c2 : Update
@enduml

@startuml user_database

    enum blocked_reason {
        unspecified
        harassment
        illegal_content
        griefing
        other
    }

    enum acct_status {
        active
        banned
    }

    object users {
        -guid id <b>key</b>
        -string username
        -string password
        -acct_status status
        +string nickname
        +string avatarURL
        -blob preferences
    }

    object friends {
        -guid id <b>key</b>
        #guid other_id
        #timestamp last_seen
    }

    object blocking {
        -guid id <b>key</b>
        #guid blocking_id
        #blocked_reason reason
        #string reason2
    }

    users::id "1" --> "n" friends::other_id 
    users::id "1" --> "n" blocking::other_id 

    note "Associations must\nbe symmetrical" as N1
    N1 .. friends

@enduml